CREATE database intuitiveCare;
use intuitiveCare;

#CRIAÇÃO DAS TABELAS QUE RECEBERÃO OS DADOS IMPORTADOS CSV

create table 1T2018(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 1T2019(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 2T2018(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 2T2019(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 3T2018(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 3T2019(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 4T2018(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table 4T2019(
DAT datetime,
REG_ANS int,
CD_CONTA_CONTABIL int PRIMARY KEY,
DESCRICAO text,
VL_SALDO_FINAL float
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

#IMPORTAÇÃO DOS CSVs

SHOW VARIABLES LIKE "secure_file_priv";

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/1T2018.csv'
INTO TABLE 1T2018
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/1T2019.csv'
INTO TABLE 1T2019
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/2T2018.csv'
INTO TABLE 2T2018
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/2T2019.csv'
INTO TABLE 2T2019
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/3T2018.csv'
INTO TABLE 3T2018
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/3T2019.csv'
INTO TABLE 3T2019
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/4T2018.csv'
INTO TABLE 4T2018
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/4T2019.csv'
INTO TABLE 4T2019
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(@DAT,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_FINAL)
SET DAT = STR_TO_DATE(@DAT, '%d/%m/%Y');

#Quais as 10 operadoras que mais tiveram despesas com "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" no último trimestre?

SELECT CD_CONTA_CONTABIL, VL_SALDO_FINAL FROM 4T2019 WHERE DESCRICAO LIKE 'EVENTOS/SINISTROS%' 
GROUP BY CD_CONTA_CONTABIL ORDER BY VL_SALDO_FINAL DESC LIMIT 10;

#Quais as 10 operadoras que mais tiveram despesas com "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" no último ano?

SELECT CD_CONTA_CONTABIL, VL_SALDO_FINAL, DESCRICAO FROM 1T2019 WHERE DESCRICAO LIKE 'EVENTOS/SINISTROS%' 
UNION
SELECT CD_CONTA_CONTABIL, VL_SALDO_FINAL, DESCRICAO FROM 2T2019 WHERE DESCRICAO LIKE 'EVENTOS/SINISTROS%' 
UNION 
SELECT CD_CONTA_CONTABIL, VL_SALDO_FINAL, DESCRICAO FROM 3T2019 WHERE DESCRICAO LIKE 'EVENTOS/SINISTROS%' 
UNION
SELECT CD_CONTA_CONTABIL, VL_SALDO_FINAL, DESCRICAO FROM 4T2019 WHERE DESCRICAO LIKE 'EVENTOS/SINISTROS%' 
GROUP BY CD_CONTA_CONTABIL ORDER BY VL_SALDO_FINAL DESC LIMIT 10;



