USE intuitivecare;

create table Relatorio_cadop(
REG_ANS INT PRIMARY KEY,
CNPJ int,
RAZÃO_SOCIAL VARCHAR(200) NOT NULL UNIQUE,
NOME_FANTASIA VARCHAR(100) NOT NULL UNIQUE,
MODALIDADE VARCHAR(100),
LOGRADOURO VARCHAR(200),
NUMERO INT,
COMPLEMENTO VARCHAR(80),
BAIRRO VARCHAR (50),
CIDADE VARCHAR(70),
UF CHAR(2),
CEP INT,
DD CHAR(2),
TELEFONE INT UNIQUE,
FAX INT,
EMAIL VARCHAR(150) NOT NULL UNIQUE,
REPRESENTANTE VARCHAR(100),
CARGO_REPRESENTANTE VARCHAR(80),
DATA_REGISTRO_ANS DATE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Query/Relatorio_cadop.csv'
INTO TABLE Relatorio_cadop
CHARACTER SET UTF8
FIELDS terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 ROWS
(REGISTRO_ANS,CNPJ,RAZAO_SOCIAL,NOME_FANTASIA,MODALIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,
UF,CEP,DDD,TELEFONE,FAX,EMAIL,CARGO_REPRESENTANTE,@DATA_REGISTRO_ANS)
SET DATA_REGISTRO_ANS = STR_TO_DATE(@DATA_REGISTRO_ANS, '%d/%m/%Y');